# Generated by Django 6.0.2 on 2026-02-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('description', models.TextField(verbose_name='Dori haqida')),
                ('usage', models.TextField(verbose_name='Nimaga ishlatiladi')),
                ('side_effects', models.TextField(verbose_name="Nojo'ya ta'siri")),
            ],
        ),
    ]
