# Generated by Django 6.0.2 on 2026-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drug_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Dori rasmi'),
        ),
    ]
